cmd_/home/elmuli/DevLop/LinuxOS/linux/tools/objtool/librbtree.o := gcc -Wp,-MD,/home/elmuli/DevLop/LinuxOS/linux/tools/objtool/.librbtree.o.d -Wp,-MT,/home/elmuli/DevLop/LinuxOS/linux/tools/objtool/librbtree.o -std=gnu11 -fomit-frame-pointer -O2 -g -Werror -Wall -Wextra -Wmissing-prototypes -Wmissing-declarations -Wwrite-strings -Wno-implicit-fallthrough -Wno-sign-compare -Wno-unused-parameter -I/home/elmuli/DevLop/LinuxOS/linux/tools/include -I/home/elmuli/DevLop/LinuxOS/linux/tools/include/uapi -I/home/elmuli/DevLop/LinuxOS/linux/tools/arch/x86/include/uapi -I/home/elmuli/DevLop/LinuxOS/linux/tools/arch/x86/include -I/home/elmuli/DevLop/LinuxOS/linux/tools/objtool/include -I/home/elmuli/DevLop/LinuxOS/linux/tools/objtool/arch/x86/include -I/home/elmuli/DevLop/LinuxOS/linux/tools/objtool/libsubcmd/include -DBUILD_KLP -DDISASM_INIT_STYLED -DDISAS -DPACKAGE=objtool -D"BUILD_STR(s)=$(pound)s" -c -o /home/elmuli/DevLop/LinuxOS/linux/tools/objtool/librbtree.o ../lib/rbtree.c

source_/home/elmuli/DevLop/LinuxOS/linux/tools/objtool/librbtree.o := ../lib/rbtree.c

deps_/home/elmuli/DevLop/LinuxOS/linux/tools/objtool/librbtree.o := \
  /usr/include/stdc-predef.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/linux/rbtree_augmented.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/linux/compiler.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/linux/compiler_types.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/linux/compiler-gcc.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/linux/types.h \
  /usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/include/stdbool.h \
  /usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/include/stddef.h \
  /usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/include/stdint.h \
  /usr/include/stdint.h \
  /usr/include/bits/libc-header-start.h \
  /usr/include/features.h \
  /usr/include/features-time64.h \
  /usr/include/bits/wordsize.h \
  /usr/include/bits/timesize.h \
  /usr/include/sys/cdefs.h \
  /usr/include/bits/long-double.h \
  /usr/include/gnu/stubs.h \
  /usr/include/gnu/stubs-64.h \
  /usr/include/bits/types.h \
  /usr/include/bits/typesizes.h \
  /usr/include/bits/time64.h \
  /usr/include/bits/wchar.h \
  /usr/include/bits/stdint-intn.h \
  /usr/include/bits/stdint-uintn.h \
  /usr/include/bits/stdint-least.h \
  /usr/include/asm/types.h \
  /usr/include/asm-generic/types.h \
  /usr/include/asm-generic/int-ll64.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/uapi/asm/bitsperlong.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/arch/x86/include/uapi/asm/bitsperlong.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/asm-generic/bitsperlong.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/uapi/asm-generic/bitsperlong.h \
  /usr/include/asm/posix_types.h \
  /usr/include/asm/posix_types_64.h \
  /usr/include/asm-generic/posix_types.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/linux/rbtree.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/linux/kernel.h \
  /usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/include/stdarg.h \
  /usr/include/assert.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/linux/build_bug.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/linux/math.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/linux/panic.h \
  /usr/include/stdio.h \
  /usr/include/bits/types/__fpos_t.h \
  /usr/include/bits/types/__mbstate_t.h \
  /usr/include/bits/types/__fpos64_t.h \
  /usr/include/bits/types/__FILE.h \
  /usr/include/bits/types/FILE.h \
  /usr/include/bits/types/struct_FILE.h \
  /usr/include/bits/types/cookie_io_functions_t.h \
  /usr/include/bits/stdio_lim.h \
  /usr/include/bits/floatn.h \
  /usr/include/bits/floatn-common.h \
  /usr/include/bits/stdio.h \
  /usr/include/stdlib.h \
  /usr/include/bits/waitflags.h \
  /usr/include/bits/waitstatus.h \
  /usr/include/sys/types.h \
  /usr/include/bits/types/clock_t.h \
  /usr/include/bits/types/clockid_t.h \
  /usr/include/bits/types/time_t.h \
  /usr/include/bits/types/timer_t.h \
  /usr/include/endian.h \
  /usr/include/bits/endian.h \
  /usr/include/bits/endianness.h \
  /usr/include/bits/byteswap.h \
  /usr/include/bits/uintn-identity.h \
  /usr/include/sys/select.h \
  /usr/include/bits/select.h \
  /usr/include/bits/types/sigset_t.h \
  /usr/include/bits/types/__sigset_t.h \
  /usr/include/bits/types/struct_timeval.h \
  /usr/include/bits/types/struct_timespec.h \
  /usr/include/bits/pthreadtypes.h \
  /usr/include/bits/thread-shared-types.h \
  /usr/include/bits/pthreadtypes-arch.h \
  /usr/include/bits/atomic_wide_counter.h \
  /usr/include/bits/struct_mutex.h \
  /usr/include/bits/struct_rwlock.h \
  /usr/include/alloca.h \
  /usr/include/bits/stdlib-bsearch.h \
  /usr/include/bits/stdlib-float.h \
  /usr/include/byteswap.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/linux/container_of.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/uapi/linux/stddef.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/linux/export.h \

/home/elmuli/DevLop/LinuxOS/linux/tools/objtool/librbtree.o: $(deps_/home/elmuli/DevLop/LinuxOS/linux/tools/objtool/librbtree.o)

$(deps_/home/elmuli/DevLop/LinuxOS/linux/tools/objtool/librbtree.o):
