cmd_/home/elmuli/DevLop/LinuxOS/linux/tools/objtool/weak.o := gcc -Wp,-MD,/home/elmuli/DevLop/LinuxOS/linux/tools/objtool/.weak.o.d -Wp,-MT,/home/elmuli/DevLop/LinuxOS/linux/tools/objtool/weak.o -std=gnu11 -fomit-frame-pointer -O2 -g -Werror -Wall -Wextra -Wmissing-prototypes -Wmissing-declarations -Wwrite-strings -Wno-implicit-fallthrough -Wno-sign-compare -Wno-unused-parameter -I/home/elmuli/DevLop/LinuxOS/linux/tools/include -I/home/elmuli/DevLop/LinuxOS/linux/tools/include/uapi -I/home/elmuli/DevLop/LinuxOS/linux/tools/arch/x86/include/uapi -I/home/elmuli/DevLop/LinuxOS/linux/tools/arch/x86/include -I/home/elmuli/DevLop/LinuxOS/linux/tools/objtool/include -I/home/elmuli/DevLop/LinuxOS/linux/tools/objtool/arch/x86/include -I/home/elmuli/DevLop/LinuxOS/linux/tools/objtool/libsubcmd/include -DBUILD_KLP -DDISASM_INIT_STYLED -DDISAS -DPACKAGE=objtool -D"BUILD_STR(s)=$(pound)s" -c -o /home/elmuli/DevLop/LinuxOS/linux/tools/objtool/weak.o weak.c

source_/home/elmuli/DevLop/LinuxOS/linux/tools/objtool/weak.o := weak.c

deps_/home/elmuli/DevLop/LinuxOS/linux/tools/objtool/weak.o := \
  /usr/include/stdc-predef.h \
  /usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/include/stdbool.h \
  /usr/include/errno.h \
  /usr/include/features.h \
  /usr/include/features-time64.h \
  /usr/include/bits/wordsize.h \
  /usr/include/bits/timesize.h \
  /usr/include/sys/cdefs.h \
  /usr/include/bits/long-double.h \
  /usr/include/gnu/stubs.h \
  /usr/include/gnu/stubs-64.h \
  /usr/include/bits/errno.h \
  /usr/include/linux/errno.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/uapi/asm/errno.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/arch/x86/include/uapi/asm/errno.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/uapi/asm-generic/errno.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/uapi/asm-generic/errno-base.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/objtool/include/objtool/objtool.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/linux/list.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/linux/types.h \
  /usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/include/stddef.h \
  /usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/include/stdint.h \
  /usr/include/stdint.h \
  /usr/include/bits/libc-header-start.h \
  /usr/include/bits/types.h \
  /usr/include/bits/typesizes.h \
  /usr/include/bits/time64.h \
  /usr/include/bits/wchar.h \
  /usr/include/bits/stdint-intn.h \
  /usr/include/bits/stdint-uintn.h \
  /usr/include/bits/stdint-least.h \
  /usr/include/asm/types.h \
  /usr/include/asm-generic/types.h \
  /usr/include/asm-generic/int-ll64.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/uapi/asm/bitsperlong.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/arch/x86/include/uapi/asm/bitsperlong.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/asm-generic/bitsperlong.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/uapi/asm-generic/bitsperlong.h \
  /usr/include/asm/posix_types.h \
  /usr/include/asm/posix_types_64.h \
  /usr/include/asm-generic/posix_types.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/linux/poison.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/linux/kernel.h \
  /usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/include/stdarg.h \
  /usr/include/assert.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/linux/build_bug.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/linux/compiler.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/linux/compiler_types.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/linux/compiler-gcc.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/linux/math.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/linux/panic.h \
  /usr/include/stdio.h \
  /usr/include/bits/types/__fpos_t.h \
  /usr/include/bits/types/__mbstate_t.h \
  /usr/include/bits/types/__fpos64_t.h \
  /usr/include/bits/types/__FILE.h \
  /usr/include/bits/types/FILE.h \
  /usr/include/bits/types/struct_FILE.h \
  /usr/include/bits/types/cookie_io_functions_t.h \
  /usr/include/bits/stdio_lim.h \
  /usr/include/bits/floatn.h \
  /usr/include/bits/floatn-common.h \
  /usr/include/bits/stdio.h \
  /usr/include/stdlib.h \
  /usr/include/bits/waitflags.h \
  /usr/include/bits/waitstatus.h \
  /usr/include/sys/types.h \
  /usr/include/bits/types/clock_t.h \
  /usr/include/bits/types/clockid_t.h \
  /usr/include/bits/types/time_t.h \
  /usr/include/bits/types/timer_t.h \
  /usr/include/endian.h \
  /usr/include/bits/endian.h \
  /usr/include/bits/endianness.h \
  /usr/include/bits/byteswap.h \
  /usr/include/bits/uintn-identity.h \
  /usr/include/sys/select.h \
  /usr/include/bits/select.h \
  /usr/include/bits/types/sigset_t.h \
  /usr/include/bits/types/__sigset_t.h \
  /usr/include/bits/types/struct_timeval.h \
  /usr/include/bits/types/struct_timespec.h \
  /usr/include/bits/pthreadtypes.h \
  /usr/include/bits/thread-shared-types.h \
  /usr/include/bits/pthreadtypes-arch.h \
  /usr/include/bits/atomic_wide_counter.h \
  /usr/include/bits/struct_mutex.h \
  /usr/include/bits/struct_rwlock.h \
  /usr/include/alloca.h \
  /usr/include/bits/stdlib-bsearch.h \
  /usr/include/bits/stdlib-float.h \
  /usr/include/byteswap.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/linux/container_of.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/linux/hashtable.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/linux/bitops.h \
  /usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/include/limits.h \
  /usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/include/syslimits.h \
  /usr/include/limits.h \
  /usr/include/bits/posix1_lim.h \
  /usr/include/bits/local_lim.h \
  /usr/include/linux/limits.h \
  /usr/include/bits/pthread_stack_min-dynamic.h \
  /usr/include/bits/pthread_stack_min.h \
  /usr/include/bits/posix2_lim.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/linux/bits.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/vdso/bits.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/vdso/const.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/uapi/linux/const.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/uapi/linux/bits.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/linux/overflow.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/asm-generic/bitops.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/asm-generic/bitops/__ffs.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/asm-generic/bitops/__ffz.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/asm-generic/bitops/fls.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/asm-generic/bitops/__fls.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/asm-generic/bitops/fls64.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/asm-generic/bitops/hweight.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/asm-generic/bitops/arch_hweight.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/asm-generic/bitops/const_hweight.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/asm-generic/bitops/atomic.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/asm-generic/bitops/non-atomic.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/linux/hash.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/linux/log2.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/objtool/include/objtool/elf.h \
  /usr/include/gelf.h \
  /usr/include/libelf.h \
  /usr/include/elf.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/linux/string.h \
  /usr/include/string.h \
  /usr/include/bits/types/locale_t.h \
  /usr/include/bits/types/__locale_t.h \
  /usr/include/strings.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/linux/rbtree.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/uapi/linux/stddef.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/linux/jhash.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/include/linux/unaligned/packed_struct.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/objtool/include/objtool/endianness.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/objtool/include/objtool/checksum_types.h \
  /usr/include/xxhash.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/objtool/arch/x86/include/arch/elf.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/objtool/include/objtool/arch.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/objtool/include/objtool/cfi.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/objtool/arch/x86/include/arch/cfi_regs.h \
  /usr/include/bfd.h \
  /usr/include/ansidecl.h \
  /usr/include/symcat.h \
  /usr/include/time.h \
  /usr/include/bits/time.h \
  /usr/include/bits/types/struct_tm.h \
  /usr/include/bits/types/struct_itimerspec.h \
  /usr/include/diagnostics.h \
  /usr/include/sys/stat.h \
  /usr/include/bits/stat.h \
  /usr/include/bits/struct_stat.h \
  /usr/include/inttypes.h \
  /usr/include/dis-asm.h \
  /usr/include/bfd.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/objtool/include/objtool/builtin.h \
  /home/elmuli/DevLop/LinuxOS/linux/tools/objtool/libsubcmd/include/subcmd/parse-options.h \

/home/elmuli/DevLop/LinuxOS/linux/tools/objtool/weak.o: $(deps_/home/elmuli/DevLop/LinuxOS/linux/tools/objtool/weak.o)

$(deps_/home/elmuli/DevLop/LinuxOS/linux/tools/objtool/weak.o):
